version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    ports:
      - '3306:3306'
    tty: true